### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by gep13**

### CODE REVIEW

**Comment by gep13** [comment]
@devlead also, any thoughts on why the build would be failing?

**Comment by gep13** [comment]
@patriksvensson would love for you to take a look at this as well :smile:

**Comment by devlead** [comment]
@gep13 think error is a path relative to script and tools issue, we have an different folder structure. I will hack together something quickly that just works to test my theory.

**Comment by gep13** [comment]
@devlead @patriksvensson ok, I see now why the build is failing on AppVeyor :-(  The build was passing on my machine because I had another version of dupfinder and inspectcode installed, via Chocolatey, which meant even though I was restoring a version of the ReSharper Commandline Tools as part of my build, that version wasn't actually being used.  When I removed those exe's from the path, I was able to replicate the issue that AppVeyor is having.

Debugging Cake, I can see that the problem is here:

image

where `toolPath == null`.  This is due to the fact that the build.cake file I am no executing is here:

image

Rather than in the root of my project folder here:

image

In this situation, should I be explicitly stating where the Tool is located?

**Comment by devlead** [comment]
@gep13 I just make a terrible "hack" to get this working, some which probably is where we are heading :)

Issue is that working dir is based of the launched script, to keep current folder structure this is what i changed.
1. Changed default build script in `.\build.ps1`
   image
2. Moved variables & args declaration to `setup.cake` so it looked like this:

``` csharp
///////////////////////////////////////////////////////////////////////////////
// ARGUMENTS
///////////////////////////////////////////////////////////////////////////////
var target          = Argument<string>("target", "Default");
var configuration   = Argument<string>("configuration", "Release");

///////////////////////////////////////////////////////////////////////////////
// GLOBAL VARIABLES
///////////////////////////////////////////////////////////////////////////////
var isLocalBuild        = !AppVeyor.IsRunningOnAppVeyor;
var isPullRequest       = AppVeyor.Environment.PullRequest.IsPullRequest;
var isDevelopBranch     = AppVeyor.Environment.Repository.Branch == "develop";
var isTag               = AppVeyor.Environment.Repository.Tag.IsTag;
var solution            = "./Source/ReSharperReports.sln";
var solutionPath        = "./Source/ReSharperReports";
var sourcePath          = "./Source";
var binDir              = "./Source/ReSharperReports/bin/" + configuration;
var buildArtifacts      = "./BuildArtifacts";
var version             = "0.2.0";
var semVersion          = "0.2.0";
var assemblyInfo        = new AssemblyInfoSettings {
                                Title                   = "ReSharperReports",
                                Description             = "Command line tool to allow generation of human readable ReSharper Reports",
                                Product                 = "ReSharperReports",
                                Company                 = "gep13",
                                Version                 = version,
                                FileVersion             = version,
                                InformationalVersion    = semVersion,
                                Copyright               = string.Format("Copyright © gep13 and Contributors {0} - Present", DateTime.Now.Year),
                                CLSCompliant            = true
                            };
var nuGetPackSettings   = new NuGetPackSettings {
                                Id                      = assemblyInfo.Product,
                                Version                 = assemblyInfo.InformationalVersion,
                                Title                   = assemblyInfo.Title,
                                Authors                 = new[] {assemblyInfo.Company},
                                Owners                  = new[] {assemblyInfo.Company},
                                Description             = assemblyInfo.Description,
                                Summary                 = "Command line tool to allow generation of human readable ReSharper Reports",
                                ProjectUrl              = new Uri("https://github.com/gep13/ReSharperReports/"),
                                LicenseUrl              = new Uri("https://github.com/gep13/ReSharperReports/blob/master/LICENSE"),
                                Copyright               = assemblyInfo.Copyright,
                                ReleaseNotes            = new List<string>() { "https://github.com/gep13/ReSharperReports/releases" },
                                Tags                    = new [] {"ReSharper", "DupFinder", "InspectCode", "Reports"},
                                RequireLicenseAcceptance= false,
                                Symbols                 = false,
                                NoPackageAnalysis       = true,
                                Files                   = new [] {
                                                                    new NuSpecContent {Source = "ReSharperReports.exe", Target = "tools"},
                                                                    new NuSpecContent {Source = "ReSharperReports.pdb", Target = "tools"},
                                                                    new NuSpecContent {Source = "ReSharperReports.xml", Target = "tools"}
                                                                 },
                                BasePath                = binDir,
                                OutputDirectory         = buildArtifacts
                            };

#l .\Tools\gep13.DefaultBuild\Content\build.cake
```

3.After that my `.\Tools\gep13.DefaultBuild\Content\build.cake` looked like this.

``` csharp
///////////////////////////////////////////////////////////////////////////////
// SETUP / TEARDOWN
///////////////////////////////////////////////////////////////////////////////

Setup(() =>
{
    // Executed BEFORE the first task.
    Information("Running tasks...");
});

Teardown(() =>
{
    // Executed AFTER the last task.
    Information("Finished running tasks.");
});

///////////////////////////////////////////////////////////////////////////////
// TASK DEFINITIONS
///////////////////////////////////////////////////////////////////////////////

Task("Clean")
    .Does(() =>
{
    Information("Cleaning {0}", solutionPath);
    CleanDirectories(solutionPath + "/**/bin/" + configuration);
    CleanDirectories(solutionPath + "/**/obj/" + configuration);

    Information("Cleaning BuildArtifacts");
    CleanDirectories(buildArtifacts);
});

Task("Restore")
    .Does(() =>
{
    // Restore all NuGet packages.
    Information("Restoring {0}...", solution);
    NuGetRestore(solution);
});

Task("SolutionInfo")
    .IsDependentOn("Clean")
    .IsDependentOn("Restore")
    .Does(() =>
{
    var file = sourcePath + "/SolutionInfo.cs";
    CreateAssemblyInfo(file, assemblyInfo);
});

Task("Build")
    .IsDependentOn("Clean")
    .IsDependentOn("Restore")
    .IsDependentOn("SolutionInfo")
    .IsDependentOn("DupFinder")
    .IsDependentOn("InspectCode")
    .Does(() =>
{
    Information("Building {0}", solution);
    MSBuild(solution, settings =>
        settings.SetPlatformTarget(PlatformTarget.MSIL)
            .WithProperty("TreatWarningsAsErrors","true")
            .WithTarget("Build")
            .SetConfiguration(configuration));
});

Task("DupFinder")
    .IsDependentOn("Create-Build-Directories")
    .Does(() =>
{
    // Run ReSharper's DupFinder
    DupFinder(solution, new DupFinderSettings() {
        ShowStats = true,
        ShowText = true,
        OutputFile = buildArtifacts + "/_ReSharperReports/dupfinder.xml"
    });
});

Task("InspectCode")
    .IsDependentOn("Create-Build-Directories")
    .Does(() =>
{
    // Run ReSharper's InspectCode
    InspectCode(solution, new InspectCodeSettings() {
        SolutionWideAnalysis = true,
        Profile = sourcePath + "/ReSharperReports.sln.DotSettings",
        OutputFile = buildArtifacts + "/_ReSharperReports/inspectcode.xml"
    });
});

Task("Create-Build-Directories")
    .Does(() =>
{
    if (!DirectoryExists(buildArtifacts))
    {
        CreateDirectory(buildArtifacts);
    }

    if (!DirectoryExists(buildArtifacts + "/_ReSharperReports"))
    {
        CreateDirectory(buildArtifacts + "/_ReSharperReports");
    }
});

Task("Create-NuGet-Package")
    .IsDependentOn("Build")
    .IsDependentOn("Create-Build-Directories")
    .Does(() =>
{
    NuGetPack(nuGetPackSettings);
});

Task("Publish-Nuget-Package")
    .IsDependentOn("Create-NuGet-Package")
    .WithCriteria(() => !isLocalBuild)
    .WithCriteria(() => !isPullRequest)
    .Does(() =>
{
    // Resolve the API key.
    var apiKey = EnvironmentVariable("MYGET_DEVELOP_API_KEY");
    if(!isDevelopBranch)
    {
        apiKey = EnvironmentVariable("MYGET_MASTER_API_KEY");
    }

    if(isTag) {
        apiKey = EnvironmentVariable("NUGET_API_KEY");
    }

    if(string.IsNullOrEmpty(apiKey)) {
        throw new InvalidOperationException("Could not resolve MyGet/Nuget API key.");
    }

    var source = EnvironmentVariable("MYGET_DEVELOP_SOURCE");
    if(!isDevelopBranch)
    {
        source = EnvironmentVariable("MYGET_MASTER_SOURCE");
    }

    if(isTag) {
        source = EnvironmentVariable("NUGET_SOURCE");
    }

    if(string.IsNullOrEmpty(source)) {
        throw new InvalidOperationException("Could not resolve MyGet/Nuget source.");
    }

    // Get the path to the package.
    var package = buildArtifacts + "/ReSharperReports." + semVersion + ".nupkg";

    // Push the package.
    NuGetPush(package, new NuGetPushSettings {
        Source = source,
        ApiKey = apiKey
    });
});

Task("Default")
    .IsDependentOn("Create-NuGet-Package");

Task("AppVeyor")
    .IsDependentOn("Publish-Nuget-Package");

///////////////////////////////////////////////////////////////////////////////
// EXECUTION
///////////////////////////////////////////////////////////////////////////////

RunTarget(target);
```

**Comment by gep13** [comment]
Ok, I see where you are going with this.

Is this approach still similar to what you do internally, or am I heading off in a different direction?

**Comment by devlead** [comment]
@gep13 this was the 30 second way to get it working :) Difference we have our tools folder relative to a build.cake that references the nuget build.cake & repo setup.cake 

Our build.ps1 creates this file if it doesn't exist and it's basically the glue between common & custom. and gitigored by default.

**Comment by devlead** [comment]
@gep13  for us the glu basically has pseudo simplified this code

``` csharp
#l [relative path to common nuget]/arguments.cake
#l [relative path to repo root]/setup.cake
#l [relative path to common nuget]/build.cake
```

arguments.cake is simplified this code:

``` csharp
///////////////////////////////////////////////////////////////////////////////
// ARGUMENTS
///////////////////////////////////////////////////////////////////////////////
var target          = Argument<string>("target", "Default");
var configuration   = Argument<string>("configuration", "Release");
```

**Comment by gep13** [comment]
Sweet!  I think I have it now.  Will implement my interpretation of it, and see if I can get everything working.  Thanks for all your help!

**Comment by devlead** [comment]
@gep13 the real gotcha is that paths are based on the script that's includes the other scripts.

**Comment by gep13** [comment]
@devlead when you ran this, did all the tasks execute successfully?

I am getting an error when trying to create the NuGet package:

image

**Comment by devlead** [comment]
Did you move the arguments too? Got this when it didn't get configuration.

**Comment by devlead** [comment]
On cell now but looks like your setup.cake is empty?

**Comment by gep13** [comment]
I haven't pushed to repo yet, just running locally.

Have got it working now though, it was the setting up of the targets.  I still had that in build.cake, but once moved into setup.cake, it is working again.

Thanks!

**Comment by devlead** [comment]
@gep13 it compiles :+1:

**Comment by gep13** [comment]
It certainly does! I am running into another issue now, but that is something completely different.  Need to do some investigation.

**Comment by gep13** [comment]
Going to go ahead and close this, and start again with new understanding of how things work :smile:

**Pull request closed without merging**
